/**
 * @file    example.c
 * @brief   Modbus RTU Multi-Instance Server Example
 * @version 2.1.0
 * @date    2026
 *
 * @details This example demonstrates how:
 *          1. Define a physical register data source.
 *          2. Initialize two independent Modbus instances (UART1 and UART2)
 *          3. Allow two instances to share the same data source ("dual
 *             interfaces accessing the same data source")
 *          4. Implement callback handling for custom function code 0x64
 *
 * @note    This file is for sample code only; actual use requires modification
 *          based on hardware configuration. CubeMX configuration requirements:
 *          - Enable USART1 and USART2
 *          - Enable the corresponding NVIC interrupt
 *          - If using RS485, configure the DE/RE control pin as GPIO Output.
 */

/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include "modbus-server.h"
#include <string.h>

/* ============================================================================
 * Hardware handle declaration (generated by CubeMX)
 * ==========================================================================================
 */

extern UART_HandleTypeDef huart1; /* UART1 handle */
extern UART_HandleTypeDef huart2; /* UART2 handle */

/* ============================================================================
 * Shared data source definition
 * ============================================================================
 *
 * Concurrency protection instructions:
 * =============
 * There is a risk of race conditions when multiple Modbus instances share the
 * same data.
 *
 * For STM32 Cortex-M cores:
 * - A single 8-bit or 16-bit read/write operation is atomic.
 * - 32-bit aligned read/write operations are also atomic.
 * - Compound operations involving multiple registers (such as reading 10
 * consecutive registers) are not atomic.
 *
 * Protection scheme:
 * 1. Simple solution - disable interrupts:
 *    __disable_irq();
 *    // Access shared data
 *    __enable_irq();
 *
 * 2. RTOS Solution - Using Mutex Locks:
 *    osMutexAcquire(dataMutexHandle, osWaitForever);
 *    // Access shared data
 *    osMutexRelease(dataMutexHandle);
 *
 * 3. Lock-free solution - using volatile + atomic flags:
 *    Suitable for scenarios with a single writer and multiple readers.
 *
 * For the simple application scenario in this example (main loop updating data,
 * two Modbus read-only accesses):
 * - Reading from a 16-bit register is inherently atomic.
 * - Interrupt protection can be disabled during application-level writes.
 */

/* Data area size definition */
#define DATA_COIL_COUNT 16        /* Number of coils */
#define DATA_DISCRETE_COUNT 16    /* Number of discrete inputs */
#define DATA_HOLDING_REG_COUNT 32 /* Number of holding registers */
#define DATA_INPUT_REG_COUNT 32   /* Number of input registers */

/* Shared data source - All Modbus instances access the same data */
static uint8_t g_coils[(DATA_COIL_COUNT + 7) / 8] = {0}; /* Coil storage area */
static uint8_t g_discrete_inputs[(DATA_DISCRETE_COUNT + 7) / 8] = {
    0}; /* Discrete input storage area */
static uint16_t g_holding_regs[DATA_HOLDING_REG_COUNT] = {
    0}; /* Holding register storage area */
static uint16_t g_input_regs[DATA_INPUT_REG_COUNT] = {
    0}; /* Input register storage area */

/* ============================================================================
 * Modbus instance definition
 * ==========================================================================================
 */

/* Modbus Example 1 (UART1) */
static MB_ServerHandle_t hmb1;

/* Modbus Example 2 (UART2) */
static MB_ServerHandle_t hmb2;

/* ============================================================================
 * Flash storage configuration (application layer implementation)
 * ==========================================================================================
 */

/**
 * @brief Flash storage configuration structure
 */
typedef struct {
  uint32_t magic_key;   /* Magic number identifier (0xDEADBEEF) */
  uint8_t server_addr1; /* Server address for Instance 1 */
  uint8_t server_addr2; /* Server address for Example 2 */
  uint32_t baud_rate;   /* Baud rate */
  uint8_t reserved[2];  /* Alignment padding */
} FlashConfig_t;

#define FLASH_MAGIC_KEY 0xDEADBEEF
#define DEFAULT_SERVER_ADDR1 0x01
#define DEFAULT_SERVER_ADDR2 0x02
#define DEFAULT_BAUD_RATE 115200

/* Storage configuration (in actual applications, it should be read from Flash)
 */
static FlashConfig_t g_flash_config = {.magic_key = FLASH_MAGIC_KEY,
                                       .server_addr1 = DEFAULT_SERVER_ADDR1,
                                       .server_addr2 = DEFAULT_SERVER_ADDR2,
                                       .baud_rate = DEFAULT_BAUD_RATE};

/* Baud rate index mapping table */
static const uint32_t BAUD_RATE_TABLE[] = {
    0,     /* 0: Invalid */
    1200,  /* 1 */
    2400,  /* 2 */
    4800,  /* 3 */
    9600,  /* 4 */
    19200, /* 5 */
    38400, /* 6 */
    57600, /* 7 */
    115200 /* 8: Default */
};

/* Pending configuration update flags */
static volatile bool g_config_update_pending = false;

/* ============================================================================
 * Callback function implementation
 * ==========================================================================================
 */

/**
 * @brief   Custom callback function for function code 0x65
 * @param   hmb         Modbus handle pointer
 * @param   param_type  Parameter address
 * @param   param_value Parameter value
 * @retval  status      true if successful, otherwise false
 *
 * @note    Agreement format:
 *          param_type =  0x0000: Modify server address, param_value = 1~247
 *          param_value = 0x0001: Modify the baud rate, param_value = 1~8 (per LUT)
 *          param_value = 0x0002: Modify parity, param_value = 0~2
 *
 * @warning Flash writes and system resets should be performed in the main loop,
 *          avoiding operations within an interrupt context.
 */
static bool MB_ConfigCallback(MB_ServerHandle_t *hmb, uint16_t param_type,
                              uint16_t param_value) {
  bool status = false;

  switch (param_type) {
  case 0x0000:                  /* Modify server address */
    if (!(1 <= param_value && param_value <= 247)) {
      /* Invalid server address */
      break;
    }

    /* Update runtime address */
    hmb->server_addr = (uint8_t)param_value;

    /*
     * Mark that configuration needs to be saved.
     * Actual Flash write and reset should be performed in the main loop.
     */
    g_config_update_pending = true;
    status = true;
    break;

  case 0x0001:                  /* Modify baud rate */
    if (!(1 <= param_value && param_value <= 8)) {
      /* Invalid baud index */
      break;
    }

    uint32_t new_baud = BAUD_RATE_TABLE[param_value];

    /* Update runtime baud rate */
    hmb->baud_rate = new_baud;

    /* This indicates that configuration needs to be saved. */
    g_config_update_pending = true;
    status = true;
    break;

  case 0x0002:                  /* Modify UART parity */
    if (!(0 <= param_value && param_value <= 2)) {
      /* Invalid parity */
      break;
    }

    /* Update runtime parity */
    hmb->parity = (uint8_t)param_value;

    /*
     * Mark that configuration needs to be saved.
     * Actual Flash write and reset should be performed in the main loop.
     */
    g_config_update_pending = true;
    status = true;
    break;
  }

  /* Other addresses: Not supported */
  return status;
}

/**
 * @brief  Callback function before writing (optional)
 * @param  hmb  Modbus RTU server handle
 * @param  func_code  function code
 * @param  start_addr  Starting address
 * @param  quantity  Quantity
 * @retval status  true if successful, otherwise false
 *
 * @note   Can be used to implement write access control or data validation.
 */
static bool WriteCallback(MB_ServerHandle_t *hmb, uint8_t func_code,
                          uint16_t start_addr, uint16_t quantity) {
  /* Example: Prevent writing to registers after address 100 */
  if (func_code == MB_WRITE_SINGLE_REGISTER ||
      func_code == MB_WRITE_MULTIPLE_REGISTERS) {
    if (start_addr + quantity > 100) {
      return false; /* Reject write */
    }
  }

  return true; /* Allow write access */
}

/* ============================================================================
 * Modbus initialization
 * ==========================================================================================
 */

/**
 * @brief  Initializes all Modbus instances
 * @retval true Initialization successful
 * @retval false Initialization failed
 */
static bool MB_AppInit(void) {
  /**
   * Configure shared data mapping
   * Both instances use the same data pointer, achieving "dual interface access
   * to the same data source"
   */
  MB_DataMap_t shared_data_map = {.coils = g_coils,
                                  .coil_count = DATA_COIL_COUNT,
                                  .discrete_inputs = g_discrete_inputs,
                                  .discrete_count = DATA_DISCRETE_COUNT,
                                  .holding_registers = g_holding_regs,
                                  .holding_register_count = DATA_HOLDING_REG_COUNT,
                                  .input_registers = g_input_regs,
                                  .input_register_count = DATA_INPUT_REG_COUNT};

  /* ==================== Initialize Modbus instance 1 (UART1)
   * =================== */
  MB_Config_t config1 = {
    /* UART configuration */
    .huart_p = &huart1,
    .server_addr = g_flash_config.server_addr1,
    .baud_rate = g_flash_config.baud_rate,

    /* Data mapping - using shared data */
    .data_map = shared_data_map,

    /* RS485 Configuration - Example 1: Using PA8 as the DE/RE control pin */
    .rs485 =
        {
            .enabled = true,
            .de_port = GPIOA,
            .de_pin = GPIO_PIN_8,
            .de_polarity =
                true /* Set de_pin to transmit; Reset de_pin to receive. */
        },

    /* Runtime options */
    .use_dma_tx = false,   /* Send in blocking mode */
    .use_hw_crc = true,    /* Use software CRC calculation */
    .use_crc_table = true, /* Fallback if hardware CRC unavailable */

    /* Callback function */
    .config_cb = MB_ConfigCallback,
    .write_cb = WriteCallback};

  if (!MB_Init(&hmb1, &config1)) {
    return false;
  }

  /* ==================== Initialize Modbus instance 2 (UART2)
   * =================== */
  MB_Config_t config2 = {
      /* UART configuration */
      .huart_p = &huart2,
      .server_addr = g_flash_config.server_addr2,
      .baud_rate = g_flash_config.baud_rate,

      /* Data mapping - using shared data (same as Instance 1) */
      .data_map = shared_data_map,

      /* RS485 Configuration - Example 2: Using PB5 as the DE/RE control pin */
      .rs485 =
          {
              .enabled = true,
              .de_port = GPIOB,
              .de_pin = GPIO_PIN_5,
              .de_polarity = true /* Send high level */
          },

      /* Runtime options */
      .use_dma_tx = false,
      .use_hw_crc = true,    /* Use software CRC calculation */
      .use_crc_table = true, /* Fallback if hardware CRC unavailable */

      /* Callback function */
      .config_cb = MB_ConfigCallback,
      .write_cb = NULL /* Example 2 does not use write callbacks */
  };

  if (!MB_Init(&hmb2, &config2)) {
    return false;
  }

  return true;
}

/* ============================================================================
 * HAL callback function
 * ==========================================================================================
 */

/**
 * @brief UART idle interrupt callback function
 * @note  Ensure that this function is called in stm32xxxx_it.c.
 *        Or implement it directly in this file.
 */
void HAL_UARTEx_RxEventCallback(UART_HandleTypeDef *huart_p, uint16_t Size) {
  /* Distribute to the corresponding Modbus process based on the UART instance
   */
  if (huart_p->Instance == USART1) {
    MB_RxCallback(&hmb1, Size);
  } else if (huart_p->Instance == USART2) {
    MB_RxCallback(&hmb2, Size);
  }
}

/**
 * @brief UART send completion callback function (required in DMA mode)
 */
void HAL_UART_TxCpltCallback(UART_HandleTypeDef *huart_p) {
  if (huart_p->Instance == USART1) {
    MB_TxCallback(&hmb1);
  } else if (huart_p->Instance == USART2) {
    MB_TxCallback(&hmb2);
  }
}

/* ============================================================================
 * Main function
 * ==========================================================================================
 */

/**
 * @brief Application Entry Point
 * @note  This example demonstrates a typical use case of two Modbus instances
 * sharing a data source.
 */
int main(void) {
  /* MCU initialization (code generated by CubeMX) */
  HAL_Init();
  // SystemClock_Config();
  // MX_GPIO_Init();
  // MX_USART1_UART_Init();
  // MX_USART2_UART_Init();

  /* Initialize all Modbus instances */
  if (!MB_AppInit()) {
    Error_Handler();
  }

  /* Initialize shared data (example) */
  g_holding_regs[0] = 0x1234;
  g_holding_regs[1] = 0x5678;
  g_input_regs[0] = 0;

  /* Main loop */
  uint32_t tick_count = 0;

  while (1) {
    /* ==================== Modbus Protocol Processing =================== */
    /* Two instances work in parallel, processing the data received from their
     * respective UARTs */
    MB_ServerProcessADU(&hmb1);
    MB_ServerProcessADU(&hmb2);

    /* ==================== Application Logic Example =================== */

    /*
     * Example 1: Simulated sensor data update (updates every 1000 cycles)
     * Note : If high data consistency is required,
     *        it is recommended to use critical section protection.
     */
    /**
     * __disable_irq();
     * g_input_regs[0] = new_value;
     * __enable_irq();
     */
    if (++tick_count >= 1000) {
      tick_count = 0;

      /* Simulate ADC sampled values ​​*/
      g_input_regs[0]++; /* 16-bit write, Cortex-M guarantees atomicity */

      /* Synchronize the value of register 0 to input register 1 */
      g_input_regs[1] = g_holding_regs[0];
    }

    /* Example 2: Using coil 0 to control an LED (assuming PC13 is connected to
     * the LED) */
    if (g_coils[0] & 0x01) {
      HAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, GPIO_PIN_RESET); /* LED ON */
    } else {
      HAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, GPIO_PIN_SET); /* LED OFF */
    }

    /**
     * Example 3: Handling configuration update requests
     * The 0x64 function code callback only sets the flag; the actual Flash
     * operation is executed here. This avoids time-consuming Flash operations
     * in the interrupt context.
     */
    if (g_config_update_pending) {
      g_config_update_pending = false;

      /* Update configuration structure */
      g_flash_config.server_addr1 = hmb1.server_addr;
      g_flash_config.baud_rate1 = hmb1.baud_rate;
      g_flash_config.parity1 = hmb1.parity;

      g_flash_config.server_addr2 = hmb2.server_addr;
      g_flash_config.baud_rate2 = hmb2.baud_rate;
      g_flash_config.parity2 = hmb2.parity;

      /**
       *  TODO: Save configuration to Flash
       * Flash_SaveConfig(&g_flash_config);
       *
       * Restart after delay:
       * HAL_Delay(50);
       * NVIC_SystemReset();
       */
    }

    /* Other application logic... */
  }
}

/**
 * @brief error handling function
 */
void Error_Handler(void) {
  __disable_irq();
  while (1) {
    /* Users can add error indicators here, such as flashing LEDs */
  }
}
